image: gitpod/workspace-python

ports:
  - port: 5000
    description: USMB - Website
  - port: 5001
    description: USMB - API
    
tasks:
  - init: cd manifest/ && chmod +x MariaDB.sh && ./manifest/MariaDB.sh
    command: echo "pret!"


vscode:
  extensions:
    - ms-python.python
